---
title: "Validation"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
---

The menu `r menuselection('Merging Data','Validation')` allows to compare satellite rainfall products and merged data products from CDT (rainfall and temperature) with station measurements using statistical indicators. To perform validation for precipitation,  go to the sub-menu `r menuselection('Precipitation')` and to the sub-menu `r menuselection('Temperature')` for temperature. A tabbed panel will be activated on the left panel, it gives you a way to enter the input, set all parameters, display map to select the area of interest, calculate the statistics and display the results.

The first tab **General** is dedicated to the required input files and directory and output directory.

`r put.image("images/merging_data/validation/tab1.png", height = 50, width = 50)`

1. Select the time step of the data.
2. Select the file containing the station validation data. If the file is not yet listed, use the button `r button('...')` to open it.
3. Enter the full path to directory containing the gridded NetCDF files, or use `r button('...')` to browse it.
4. Provide a sample file from the gridded data by selecting it from the drop-down list or open it by using the button `r button('...')`.
5. Specify the gridded data filename format. See the section [NetCDF filename format](cdt_data_input.html#cdt.ncdf.ffrmt) for more details on the format of NetCDF file names.
6. Enter the full path to directory to save the validation output, or browse it from `r button('...')`.


The tab **Select Stations** allows to select the station to be used to perform the validation.

`r put.image("images/merging_data/validation/tab2.png", height = 50, width = 50)`

1. There are three ways to select the stations to be used to do the validation:
	- __All Stations__: all the stations from the station data will be used.
	- __Rectangle__: the stations can be selected by drawing a rectangle over the region
	- __Polygons__: